// Copyright (c) 2023 khh403. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Code generated by set-gen. DO NOT EDIT.

// Package sets has auto-generated set types.
package sets
